"""added status item status

Revision ID: 6cf92f9ff225
Revises: cf70a0c2555c
Create Date: 2024-06-01 07:03:11.008775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cf92f9ff225'
down_revision = 'cf70a0c2555c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('status', sa.String(length=50), nullable=False, server_default='active'))
    # ### end Alembic commands ###

    # Remove the server default after the column is added and populated
    op.alter_column('item', 'status', server_default=None)

def downgrade():
    # Drop the column during downgrade
    op.drop_column('item', 'status')